#!/bin/bash
echo "D-Range Project"
echo "Video Streaming for the BeagleBone"

# ***** Stream Video over UDP ******
# Next line not necessary if you are using my -F option on capture
#v4l2-ctl --set-fmt-video=width=1000,height=800,pixelformat=1

# Pipe the output of capture into avconv/ffmpeg 
# capture "-F"   My H264 passthrough mode
#	  "-o"   Output the video (to be passed to avconv via pipe)
#	  "-c0"  Capture 0 frames, which means infinite frames in my program
# avconv "-re" read input at the native frame rate
#        "-i -"  Take the input from the pipe
#	 "-vcodec copy" Do not transcode the video

# 	 "-f rtp rtp://192.168.8.96:1234/" Force rtp to output to address of my PC on port 1234
./capture -F -o -c0|ffmpeg -re -i - -vcodec copy -f mpegts udp://192.168.8.96:1235
# ***** Stream Video over UDP ****** -loglevel quiet -hide_banner
# > /dev/null -loglevel quiet